# Generated by Django 5.2.6 on 2025-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(default=None, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='PhoneBook/static/images/')),
            ],
        ),
    ]
