# Generated by Django 5.2.6 on 2025-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysuperuser',
            name='adress',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mysuperuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mysuperuser',
            name='profile_picures',
            field=models.TextField(default=None, null=True),
        ),
    ]
